"""Synthetic regressions for the P1 research acceptance boundary."""

import hashlib
import json
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pandas as pd
import pytest

ad = pytest.importorskip("anndata")
pytest.importorskip("pydeseq2")

from eacbp.acceptance.manifest import AcceptanceManifest
from eacbp.acceptance.manifest import ResourceLimits
from eacbp.acceptance.runner import _compare, run_acceptance
from eacbp.artifact.registry import ArtifactRegistry
from eacbp.orchestrator.dag import ComputationalDAGPlanner
from eacbp.orchestrator.loop import ScientificOrchestrator
from eacbp.evidence.snapshot import load_study_snapshot, write_study_snapshot
from eacbp.schemas.artifact import ArtifactType
from eacbp.schemas.study import BiologicalDesign, DataSpec, StudyManifest
from eacbp.schemas.task import TaskContract


def _adata(*, n_donors=4, paired=True, confounded=False, condition_effect=False):
    rng = np.random.default_rng(1907)
    rows, obs = [], []
    for donor_index in range(n_donors):
        donor = f"d{donor_index + 1}"
        conditions = ("A", "B") if paired else (("A",) if donor_index < n_donors // 2 else ("B",))
        for condition_index, condition in enumerate(conditions):
            if confounded:
                batch = condition
            elif paired:
                batch = f"batch_{(donor_index + condition_index) % 2 + 1}"
            else:
                batch = f"batch_{donor_index % 2 + 1}"
            for _ in range(2):
                baseline = np.full(24, 30 + donor_index * 3, dtype=np.int64)
                baseline += np.arange(24, dtype=np.int64) % 7
                if condition_effect and condition == "B":
                    baseline[0] *= 4
                counts = rng.poisson(baseline).astype(np.int64)
                rows.append(counts)
                obs.append({"donor_id": donor, "condition": condition, "batch": batch})
    data = ad.AnnData(
        X=np.asarray(rows, dtype=np.float32),
        obs=pd.DataFrame(obs),
        var=pd.DataFrame(index=[f"g{i}" for i in range(24)]),
    )
    data.layers["counts"] = np.asarray(rows, dtype=np.int64)
    data.uns["species"] = "mus_musculus"
    data.uns["is_simulated"] = True
    return data


def _write_manifest(tmp_path: Path, *, n_donors=4, paired=True, confounded=False):
    data = _adata(n_donors=n_donors, paired=paired, confounded=confounded)
    h5ad_path = tmp_path / "synthetic.h5ad"
    data.write_h5ad(h5ad_path)
    digest = hashlib.sha256(h5ad_path.read_bytes()).hexdigest()
    manifest = AcceptanceManifest(
        study_id="acceptance_synthetic",
        dataset_kind="synthetic",
        data_path=h5ad_path.name,
        sha256=digest,
        source="Synthetic regression fixture generated by tests/test_research_acceptance.py",
        source_url=None,
        license="not_applicable_synthetic",
        species="mus_musculus",
        species_metadata_key="species",
        counts_layer="counts",
        contrast={"column": "condition", "tested": "B", "reference": "A"},
        donor={"column": "donor_id", "biological_unit": "mouse", "paired": paired, "minimum_per_condition": 2},
        batch_column="batch",
        covariates=["batch"] if confounded else [],
        statistics={"cooks_filter": False, "independent_filter": False},
    )
    return manifest, tmp_path


def test_nonsignificant_synthetic_design_runs_and_matches_direct_pydeseq2(tmp_path):
    manifest, manifest_dir = _write_manifest(tmp_path)
    result = run_acceptance(manifest, manifest_dir)

    assert result["statuses"] == {"engineering": "passed", "method": "passed"}
    assert result["evidence_class"] == "synthetic_software_regression"
    assert result["research_acceptance"]["status"] == "not_applicable_synthetic"
    assert result["research_acceptance"]["biological_validity_claimed"] is False
    assert result["direct_reference"]["comparison"]["status"] == "passed"
    assert result["scientific_result"]["audit"]["overall_passed"] is True
    assert result["scientific_result"]["scientific_result"]["status"] == "estimated_inconclusive"
    assert result["scientific_result"]["metrics"]["n_significant_at_alpha"] == 0
    assert result["input"]["n_cells"] == 16
    assert result["input"]["n_genes"] == 24
    assert result["design"]["n_pseudobulk_samples"] == 8
    json.dumps(result, allow_nan=False)


def test_single_donor_is_rejected_before_model_fit(tmp_path):
    manifest, manifest_dir = _write_manifest(tmp_path, n_donors=1)
    result = run_acceptance(manifest, manifest_dir)

    assert result["statuses"]["method"] == "not_run"
    assert result["failure"]["type"] == "AdvancedStatisticsInputError"
    assert "requires at least 2 donors" in result["failure"]["message"]


def test_complete_condition_batch_confounding_is_rejected(tmp_path):
    manifest, manifest_dir = _write_manifest(tmp_path, paired=False, confounded=True)
    result = run_acceptance(manifest, manifest_dir)

    assert result["statuses"]["method"] == "not_run"
    assert result["failure"]["type"] == "AdvancedStatisticsInputError"
    assert "rank deficient" in result["failure"]["message"]


@pytest.mark.parametrize(
    "eacbp_effect,reference_effect",
    [(np.inf, 1.0), (1.0, np.inf), (np.inf, -np.inf), (np.nan, np.inf)],
)
def test_direct_comparison_rejects_mismatched_nonfinite_values(tmp_path, eacbp_effect, reference_effect):
    manifest, _ = _write_manifest(tmp_path)
    table = pd.DataFrame({
        "gene": ["g0"], "log2_fold_change": [eacbp_effect],
        "ci_low": [-1.0], "ci_high": [1.0], "fdr_q_value": [0.5],
    })
    reference = pd.DataFrame({
        "log2FoldChange": [reference_effect], "lfcSE": [0.5], "padj": [0.5],
    }, index=["g0"])

    comparison = _compare(table, reference, manifest)

    assert comparison["status"] == "failed"
    assert comparison["metrics"]["effect"]["passed"] is False


def test_input_size_limit_rejects_before_h5ad_load(tmp_path, monkeypatch):
    manifest, manifest_dir = _write_manifest(tmp_path)
    manifest = manifest.model_copy(update={"resource_limits": ResourceLimits(max_input_bytes=1)})
    monkeypatch.setattr(ad, "read_h5ad", lambda *_args, **_kwargs: pytest.fail("h5ad was read before size preflight"))

    result = run_acceptance(manifest, manifest_dir)

    assert result["failure"]["type"] == "AcceptanceFailure"
    assert "rejected before loading h5ad" in result["failure"]["message"]


def test_advanced_inference_snapshot_and_resume_keep_neutral_result_ids(tmp_path):
    registry = ArtifactRegistry(str(tmp_path / "artifacts"))
    orchestrator = ScientificOrchestrator(artifact_registry=registry)
    data = _adata(n_donors=4, paired=True, condition_effect=False)
    study_id = "acceptance_recovery"
    input_uri = f"adata://{study_id}/raw/v1"
    registry.register(input_uri, data, ArtifactType.ANNDATA, study_id, "input", "raw_counts")
    manifest = StudyManifest(
        study_id=study_id,
        biological_design=BiologicalDesign(species="mus_musculus", tissue="brain", conditions=["A", "B"]),
        data=DataSpec(raw_artifact_uri=input_uri),
    )
    output_uri = f"table://{study_id}/pydeseq2/v1"

    def plan(*_args, **_kwargs):
        return [TaskContract(
            task_id="acceptance_deg",
            capability="deg",
            method="pydeseq2_pseudobulk_v1",
            input_artifacts=[input_uri],
            expected_outputs=[output_uri],
            validation_requirements=["advanced_statistics_integrity", "multiple_testing_correction", "pseudoreplication_audit"],
            parameters={
                "condition_a": "A", "condition_b": "B",
                "contrast": ["condition", "B", "A"],
                "donor_col": "donor_id", "paired": True,
                "counts_layer": "counts", "n_cpus": 1,
                "cooks_filter": False, "independent_filter": False,
            },
        )]

    capability = orchestrator.capability_registry.get("deg", "pydeseq2_pseudobulk_v1")
    actual_execute = capability.execute
    with patch.object(capability, "execute", wraps=actual_execute) as fit, \
         patch.object(ComputationalDAGPlanner, "build_study_plan", side_effect=plan):
        actual_audit = orchestrator.auditor.audit_task
        audit_calls = []

        def fail_once_then_audit(*args, **kwargs):
            audit_calls.append(1)
            if len(audit_calls) == 1:
                raise RuntimeError("interrupted audit after completed PyDESeq2 fit")
            return actual_audit(*args, **kwargs)

        with patch.object(orchestrator.auditor, "audit_task", side_effect=fail_once_then_audit):
            first = orchestrator.run_study(manifest, {"advanced_analysis": True})
            resumed = orchestrator.run_study(manifest, {"advanced_analysis": True, "resume": True})
            resumed_events = __import__("eacbp.orchestrator.events", fromlist=["read_run_events"]).read_run_events(resumed["event_log"])

        assert first["status"] == "failed"
        assert first["evidence_nodes_count"] == 0
        assert resumed["status"] == "success", resumed["failures"]
        assert fit.call_count == 1
        assert any(event.kind == "task_resumed" for event in resumed_events)

        task_result = orchestrator.task_history[0]
        assert task_result.method_used == "pydeseq2_pseudobulk_v1"
        assert task_result.scientific_result is not None
        assert task_result.inference_contract is not None
        assert len(orchestrator.evidence_graph.evidence_nodes) == 1
        evidence = next(iter(orchestrator.evidence_graph.evidence_nodes.values()))
        claim = next(iter(orchestrator.evidence_graph.claim_nodes.values()))
        assert evidence.type.value == "statistical_result"
        assert evidence.polarity.value == "neutral"
        assert claim.claim_type.value == "result_summary"
        assert evidence.inference_contract_id == task_result.inference_contract_id
        evidence_ids = list(orchestrator.evidence_graph.evidence_nodes)
        claim_ids = list(orchestrator.evidence_graph.claim_nodes)

        snapshot_path = tmp_path / "recovery.snapshot.json"
        write_study_snapshot(
            snapshot_path,
            manifest=manifest,
            config={"advanced_analysis": True},
            summary=resumed,
            evidence_graph=orchestrator.evidence_graph,
            artifact_registry=registry,
            task_history=orchestrator.task_history,
            audit_reports=orchestrator.audit_reports,
        )
        snapshot = load_study_snapshot(snapshot_path)
        assert list(snapshot.evidence_graph.evidence_nodes) == evidence_ids
        assert list(snapshot.evidence_graph.claim_nodes) == claim_ids
        assert snapshot.task_results[0].task_id == task_result.task_id
        assert snapshot.task_results[0].inference_contract_id == task_result.inference_contract_id
        assert snapshot.task_results[0].scientific_result.status == task_result.scientific_result.status

        third = orchestrator.run_study(manifest, {"advanced_analysis": True, "resume": True})

    assert third["status"] == "success", third["failures"]
    assert fit.call_count == 1
    assert list(orchestrator.evidence_graph.evidence_nodes) == evidence_ids
    assert list(orchestrator.evidence_graph.claim_nodes) == claim_ids
    assert len(evidence_ids) == len(set(evidence_ids)) == 1
    assert len(claim_ids) == len(set(claim_ids)) == 1
